seo-bundle:
  description: |
      It provides a solution to make content bundles
      aware for Search Engine Optimisation (SEO).
  branches:
    master:
      docs_path: 'bundles/seo'
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        functional_tests_orm: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
core-bundle:
  description: |
      The CoreBundle for the Symfony content management framework provides common functionality,
      helpers and utilities for the other CMF bundles. The major features are a publish workflow,
      a twig extension and php templating helper to walk PHPCR-ODM trees and support for optional translated content.
  branches:
    master:
      docs_path: 'bundles/core'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
menu-bundle:
  description: |
      The MenuBundle provides menus from a doctrine object manager with the help of KnpMenuBundle.
  branches:
    master:
      docs_path: 'bundles/menu'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
routing-bundle:
  description: |
      The RoutingBundle enables the
      [CMF Routing component](https://github.com/symfony-cmf/Routing)
      as a Symfony bundle. It provides route documents for Doctrine PHPCR-ODM and a
      controller for redirection routes.
  branches:
    master:
      docs_path: 'bundles/routing'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        functional_tests_orm: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
routing:
  description: |
      The Symfony CMF Routing component extends the Symfony routing component with additional features:

       * A ChainRouter to run several routers in parallel
       * A DynamicRouter that can load routes from any database and can generate
         additional information in the route match.

      The CMF Routing component does not need the Symfony full stack framework. It is
      also useful in applications not using the full Symfony framework.

      For the best integration into the Symfony full stack framework, it is
      recommended to use the [RoutingBundle](https://github.com/symfony-cmf/RoutingBundle)
      when building Symfony full stack applications.
  branches:
    master:
      docs_path: 'components/routing'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        unit_tests: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
content-bundle:
  description: |
      The ContentBundle provides a document for static content and the controller to render it.
  branches:
    master:
      docs_path: 'bundles/routing'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
resource-rest-bundle:
  description: |
      This Bundle provides a REST API to Puli resources as provided by the CmfResource component.
  branches:
    master:
      docs_path: 'bundles/resource-rest'
      docs_extra: |
          ## Example

          ````bash
          $ curl http://localhost:8000/api/phpcrodm_repo/foo | python -m json.tool
          {
              "_links": {
                  "self": {
                      "href": "/api/phpcrodm_repo/foo"
                  }
              },
              "children": {
                  "bar": {
                      "_links": {
                          "self": {
                              "href": "/api/phpcrodm_repo/foo/bar"
                          }
                      },
                      "children": [],
                      "document": {
                          "_links": {
                              "self": {
                                  "href": "/path/to/this"
                              }
                          },
                          "body": "This is my second article",
                          "id": "/tests/cmf/articles/foo/bar",
                          "title": "Article 2"
                      },
                      "path": "/foo/bar",
                      "repo_path": "/foo/bar"
                  },
                  "boo": {
                      "_links": {
                          "self": {
                              "href": "/api/phpcrodm_repo/foo/boo"
                          }
                      },
                      "children": [],
                      "document": {
                          "_links": {
                              "self": {
                                  "href": "/path/to/this"
                              }
                          },
                          "body": "This is my third article",
                          "id": "/tests/cmf/articles/foo/boo",
                          "title": "Article 2"
                      },
                      "path": "/foo/boo",
                      "repo_path": "/foo/boo"
                  }
              },
              "document": {
                  "_links": {
                      "self": {
                          "href": "/path/to/this"
                      }
                  },
                  "body": "This is my article",
                  "id": "/tests/cmf/articles/foo",
                  "title": "Article 1"
              },
              "path": "/foo",
              "repo_path": "/foo"
          }
          ````
          ## Running the tests

          ### Behat
          - Setup database: `./vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh`
          - Run server: `./vendor/symfony-cmf/testing/bin/server`
          - Run tests: `./vendor/bin/behat`
      php: ['7.0', '7.1']
      make_tasks:
        unit_tests: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
