seo-bundle:
  description: |
      It provides a solution to make content bundles
      aware for Search Engine Optimisation (SEO).
  branches:
    master:
      docs_path: 'bundles/seo'
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        functional_tests_orm: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
core-bundle:
  description: |
      The CoreBundle for the Symfony content management framework provides common functionality,
      helpers and utilities for the other CMF bundles. The major features are a publish workflow,
      a twig extension and php templating helper to walk PHPCR-ODM trees and support for optional translated content.
  branches:
    master:
      docs_path: 'bundles/core'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
