seo-bundle:
  description: |
    "This bundle is part of the [Symfony Content Management Framework (CMF)](http://cmf.symfony.com/)
    and licensed under the [MIT License](LICENSE).

    It provides a solution to make content bundles
    aware for Search Engine Optimisation (SEO)."
  branches:
    master:
      docs_path: 'bundles/seo'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        test_unit: ~
        test_integration_phpcr: ~
        test_integration_orm: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
