seo-bundle:
  description: |
      It provides a solution to make content bundles
      aware for Search Engine Optimisation (SEO).
  branches:
    master:
      docs_path: 'bundles/seo'
      php: ['7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        functional_tests_orm: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
core-bundle:
  description: |
      The CoreBundle for the Symfony content management framework provides common functionality,
      helpers and utilities for the other CMF bundles. The major features are a publish workflow,
      a twig extension and php templating helper to walk PHPCR-ODM trees and support for optional translated content.
  branches:
    master:
      docs_path: 'bundles/core'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
menu-bundle:
  description: |
      The MenuBundle provides menus from a doctrine object manager with the help of KnpMenuBundle.
  branches:
    master:
      docs_path: 'bundles/menu'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
routing-bundle:
  description: |
      The RoutingBundle enables the
      [CMF Routing component](https://github.com/symfony-cmf/Routing)
      as a Symfony bundle. It provides route documents for Doctrine PHPCR-ODM and a
      controller for redirection routes.
  branches:
    master:
      docs_path: 'bundles/routing'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        functional_tests_orm: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
routing:
  description: |
      The Symfony CMF Routing component extends the Symfony routing component with additional features:

       * A ChainRouter to run several routers in parallel
       * A DynamicRouter that can load routes from any database and can generate
         additional information in the route match.

      The CMF Routing component does not need the Symfony full stack framework. It is
      also useful in applications not using the full Symfony framework.

      For the best integration into the Symfony full stack framework, it is
      recommended to use the [RoutingBundle](https://github.com/symfony-cmf/RoutingBundle)
      when building Symfony full stack applications.
  branches:
    master:
      docs_path: 'components/routing'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        unit_tests: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
routing-auto:
  description: |
      This component automatically creates and manages routes for configured persisted document classes.
      This library contains all implementation agnostic code.
  branches:
    master:
      docs_path: 'components/routing'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        unit_tests: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
content-bundle:
  description: |
      The ContentBundle provides a document for static content and the controller to render it.
  branches:
    master:
      docs_path: 'bundles/routing'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
resource-rest-bundle:
  description: |
      This Bundle provides a REST API to Puli resources as provided by the CmfResource component.
  branches:
    master:
      docs_path: 'bundles/resource-rest'
      php: ['7.0', '7.1']
      make_tasks:
        unit_tests: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
resource-bundle:
  description: |
      This bundle provides *object* resource location services based on Puli.

      Examples:

      - **Static document path mapping**: Map the path `/routes` to `/cms/routes`
      - **Dynamic document resolution**: Map the path `/routes` to `/cms/<current site>/routes`.
      - **Access documents at a static location**: Map `/role/menu/main` to `/cms/menus/main-menu`.

      The first example could use the existing CMF base route configuration to
      resolve paths.

      The benefit of the above two examples would be most strongly felt in
      association with another component which would provide a context for the
      document resource resolution.

      For example, a `Site` which is matched against the incoming hostname would
      provide the context with which to resolve the documents.
  branches:
    master:
      docs_path: 'bundles/resource-rest'
      php: ['7.0', '7.1']
      make_tasks:
        unit_tests: ~
        functional_tests_phpcr: ~
        test_installation: ~
      versions:
        symfony: ['2.8', '3.1', '3.2', '3.3']
      failing_allowed_versions:
        symfony: ['3.4']
resource:
  excluded_files:
      - .travis.yml.twig
  description: |
    The Resource component provides PHPCR/ODM integration with Puli.

     > **CAUTION** As Puli is not yet stable, the complete component is marked
     > internal. Backwards compatibility of upcoming 1.x versions is not
     > guaranteed.

  branches:
    master:
      docs_path: 'components/resource'
      php: ['5.6', '7.0', '7.1']
      make_tasks:
        unit_tests: ~
